apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mariadb.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-carlier-alex-testspace-charts-test-mariadb
      app: {{ .Values.mariadb.name }}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-carlier-alex-testspace-charts-test-mariadb
        app: {{ .Values.mariadb.name }}
    spec:
      containers:
      - name: {{ .Values.mariadb.name }}
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mariadb.development.containerPort }}
          name: {{ .Values.mariadb.development.portName }}
          protocol: {{ .Values.mariadb.development.protocol }}
        envFrom:
        - secretRef:
            name: {{ .Values.env.name }}
            optional: {{ .Values.env.optional }}
        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: {{ .Values.volume.mountPath }}
      nodeName: {{ .Values.nodeName }}
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.claimName }}