apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    workload.user.cattle.io/workloadselector: "apps.deployment-{{ .Values.image.workloadselector }}"
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
