apiVersion: v2
appVersion: "1.0"
description: adminer deployment & service
home: https://helm.sh/helm
maintainers:
  - email: alex.carlier@student.howest.be
    name: Carlier Alex
name: test-adminer
sources:
  - https://github.com/helm/helm
version: 0.0.2
